### ISSUE TITLE
Request for android version

### ISSUE THREAD

**Issue by Cubetaro** [CubeStuffs/CubeTime#184]
Hello, I have one request or suggestion that I really hope that it will happen. I saw many people using cubetime but I have android which it is really sad. So can you please make an android version so i can use the timer? I will wait for it thank you!

**Comment by xbjfk** [comment]
Hi there!
Thank you for your interest in CubeTime!
Unfortunately, as CubeTime is  fully native app using SwiftUI and UIKit APIs, and therefore creating an Android version would be no small undertaking.
However, it is possible, in the far future that we may create an Android version.
Thanks.

**Comment by pdtxie** [comment]
With further discussion, we will be marking this as not planned. As @xbjfk mentioned, since the app is fully written in Swift and is native to iOS, it will be an incredible effort to port this to Android. Sorry about this, but there are many good apps out there for Android, such as https://github.com/aricneto/TwistyTimer.
